[package]
name = "ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"
rand = "0.8.5"
rust-crypto = "0.2.36"
